nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: mixed
enableTelemetry: false
enableNetwork: true
enableScripts: true
enableImmutableInstalls: false

packageExtensions:
  esbuild@*:
    dependencies:
      esbuild-linux-64: "*"